services:
    app:
        build: .
        container_name: lisakuv-obchod
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
        entrypoint: ["/app/entrypoint.sh"]
